import type { NextPage } from 'next';
import Head from 'next/head';
import SnapScroll from '../components/SnapScroll';
import styles from '../styles/Main.module.scss';

const Home: NextPage = () => {
  return (
    <div>
			<Head>
				<title>Crane Song</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
        <SnapScroll /> 
			</main>
    </div>
  );
};

export default Home;
